services:
  db:
    image: postgres:latest
    container_name: postgres_notify_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notify_service
    ports:
      - "5432:5432"
    volumes:
      - db_notify_service:/var/lib/postgresql/data

volumes:
  db_notify_service:
